[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = 'test'
cache_path = 'cache-forge'
script = 'scripts'
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# Specific EVM version since push0 isn't supported on most chains. 
evm_version = "paris"
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
